# Análisis exploratorio

En este notebook se realizará un **análisis exploratorio** de la información financiera cargada en los catálogos y en los históricos.

In [1]:
import pandas as pd

### perfil de riesgo

In [2]:
perfil = pd.read_csv('../data/cat_perfil_riesgo.csv')
print(perfil.shape)
perfil.info()

(4, 2)
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cod_perfil_riesgo  4 non-null      int64
 1   perfil_riesgo      4 non-null      str
dtypes: int64(1), str(1)
memory usage: 192.0 bytes

In [3]:
perfil.head()

   cod_perfil_riesgo perfil_riesgo
0               1469      AGRESIVO
1               1468      MODERADO
2               1466   SIN DEFINIR
3               1467   CONSERVADOR

## Catálogo Activos

In [4]:
activos = pd.read_csv('../data/catalogo_activos.csv', encoding='latin-1')
activos.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   activo      19 non-null     str
 1   cod_activo  19 non-null     int64
dtypes: int64(1), str(1)
memory usage: 432.0 bytes

In [5]:
activos.head()

                 activo  cod_activo
0  CDT BANCOLOMBIA B360        1000
1      CDT TUYA TF B360        1001
2                CELSIA        1002
3              CEMARGOS        1003
4             ECOPETROL        1004

## Catálogo Banca

In [6]:
banca = pd.read_csv('../data/catalogo_banca.csv')
banca.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cod_banca  5 non-null      str
 1   banca      5 non-null      str
dtypes: str(2)
memory usage: 208.0 bytes

In [7]:
banca.head()

  cod_banca         banca
0        PR       Privada
1        PN      Personal
2        PF  Preferencial
3        EG      Empresas
4        PY         Pymes

## Historico macroactivos

In [8]:
macroactivos = pd.read_csv('../data/historico_aba_macroactivos.csv')
macroactivos.info()

<class 'pandas.DataFrame'>
RangeIndex: 6694 entries, 0 to 6693
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ingestion_year      6694 non-null   int64
 1   ingestion_month     6690 non-null   float64
 2   ingestion_day       6694 non-null   int64
 3   id_sistema_cliente  6691 non-null   str
 4   macroactivo         6687 non-null   str
 5   cod_activo          6464 non-null   str
 6   aba                 6688 non-null   float64
 7   cod_perfil_riesgo   6575 non-null   str
 8   cod_banca           6684 non-null   str
 9   year                6693 non-null   str
 10  month               6691 non-null   float64
dtypes: float64(3), int64(2), str(6)
memory usage: 575.4 KB

In [9]:
macroactivos.sample(5)

,ingestion_year,ingestion_month,ingestion_day,id_sistema_cliente,macroactivo,cod_activo,aba,cod_perfil_riesgo,cod_banca,year,month
2223,2023,12.0,21,10039538018,FICs,10007,3.269387e+05,1468,PN,2023,12.0
5477,2023,12.0,11,1.008E+11,FICs,1019,3.183233e+08,1467,PY,2023,12.0
1379,2023,12.0,12,10042890695,FICs,10007,3.326397e+07,NaN,PN,2023,12.0
3148,2024,3.0,21,10039616197,Renta Variable,1004,2.125000e+06,1466,PN,2024,3.0
3393,2024,4.0,29,1.00105E+12,Renta Variable,1004,2.300000e+06,1466,PN,2024,4.0

In [10]:
macroactivos.isna().sum()

ingestion_year          0
ingestion_month         4
ingestion_day           0
id_sistema_cliente      3
macroactivo             7
cod_activo            230
aba                     6
cod_perfil_riesgo     119
cod_banca              10
year                    1
month                   3
dtype: int64

In [11]:
macroactivos['id_sistema_cliente'].value_counts()

id_sistema_cliente
10032184607          1004
10020203023           855
10039616197           672
1.009E+11             448
10079142847           337
1.00114E+12           336
10038643094           336
1.0089E+11            224
1.008E+11             224
1.00901E+11           114
10036346714           113
10079414250           113
1.00902E+11           112
1.00103E+12           112
10041560001           112
10071747544           112
1.00109E+12           112
10098522488           112
10026419826           112
1.00105E+12           112
1004870235            112
10042890695           112
10066848163           112
1.00101E+12           112
10021382511           112
10039538018           112
1.0083E+11            112
10014876058           112
10039553126           111
100                     8
100Renta Variable       2
1002203023              1
100FICs                 1
Name: count, dtype: int64

In [12]:
macroactivos['macroactivo'].value_counts()

macroactivo
Renta Variable    3360
FICs              3092
Renta Fija         227
32184607             3
890112256            1
20203023             1
1018                 1
1002                 1
1005                 1
Name: count, dtype: int64

In [13]:
macroactivos['cod_activo'].value_counts()

cod_activo
1004              1347
10007             1337
1019              1009
1005               559
1012               336
1014               225
1017               223
1018               223
1008               220
1022               113
1000               113
1011               112
1016               112
1020               112
1001               112
1002               110
1015               107
1010                60
1009                13
1007                 7
FICs                 5
1003                 5
650060.72            1
9480000              1
90535                1
Renta Variable       1
Name: count, dtype: int64

In [14]:
macroactivos['cod_perfil_riesgo'].value_counts()

cod_perfil_riesgo
1468           3094
1466           2350
1467            899
1469            222
PN                4
22350729.74       1
100931241.5       1
78815.51          1
78472.41          1
12615000          1
76142.74          1
Name: count, dtype: int64

In [15]:
macroactivos['cod_banca'].value_counts()

cod_banca
PN      4247
PR      1080
PF       898
PY       334
EG       114
1468       6
2024       4
1466       1
Name: count, dtype: int64

## Historico internacional

In [16]:
internacional = pd.read_csv('../data/historico_aba_usd_internacional.csv', on_bad_lines='warn')
internacional.info()

<class 'pandas.DataFrame'>
RangeIndex: 5750 entries, 0 to 5749
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ingestion_year      5750 non-null   int64
 1   ingestion_month     5750 non-null   int64
 2   ingestion_day       5750 non-null   int64
 3   id_sistema_cliente  5750 non-null   str
 4   simbol              3241 non-null   str
 5   cusip               5750 non-null   str
 6   isin                5750 non-null   str
 7   nombre_activo       5750 non-null   str
 8   cantidad            5750 non-null   str
 9   valor_mercado       5750 non-null   str
 10  fecha_vencimiento   5750 non-null   str
 11  tasa_cupon          5748 non-null   str
dtypes: int64(3), str(9)
memory usage: 539.2 KB

In [17]:
internacional.sample(5)

,ingestion_year,ingestion_month,ingestion_day,id_sistema_cliente,simbol,cusip,isin,nombre_activo,cantidad,valor_mercado,fecha_vencimiento,tasa_cupon
5065,2024,3,1,10039553126,NaN,L1049H415,LU0072462426,BGF GLOBAL ALLOCATION FUND CLASS A2 (USD),494.25,33831.41,1/01/1900,0
5081,2024,3,1,10039553126,NaN,P15383EG6,XS2737008388,BANISTMO S A MEDIUM TERM NOTES ISIN#XS27370083...,50000,50000,06/19/2025,6.25
2473,2024,3,1,10026419826,NaN,L1049H415,LU0072462426,BGF GLOBAL ALLOCATION FUND CLASS A2 (USD),632.06,47107.43,1/01/1900,0
4285,2024,3,1,10038643094,DLPG,MONEYMRKT,Liquidez,BNY MELLON US DOLLAR LIQD SERV,0,331664.19,1/01/1900,0
933,2024,3,1,1004870235,NaN,L8146B779,LU0133713346,SCHRODER ISF ASIAN OPPORTUNITIES FUND CLASS A1...,3281.6,59984.37,1/01/1900,0

In [18]:
internacional['id_sistema_cliente'].value_counts()

id_sistema_cliente
1004870235     1237
10026419826    1021
10038643094     785
10021382511     734
10041560001     523
10014876058     381
10039553126     274
10032184607     218
10036346714     199
10039616197     134
10039538018     130
10020203023     113
EPMP5694987       1
Name: count, dtype: int64

In [19]:
internacional['simbol'].value_counts()

simbol
DLPG            721
AAPL            130
USD              85
XLB              65
GOOG             65
NFLX             65
VGK              65
EEM              65
AMZN             65
DIS              65
META             65
BRK B            65
XLF              65
AVAL4362366      65
ISVFF            65
BNTM5022912      65
PBR              65
C                65
SQ               65
LYG              65
CHPT             65
SOXL             65
PYPL             65
QS               65
AMD              65
SOFI             65
PLTR             65
VGSH             65
TEF5013179       65
LILKV5006556     65
BGNB4479830      65
BAK4918586       65
BGNB5166290      65
ISVIF            46
MRVL             44
ARKK             42
ABNB             42
ECOH5689502      35
EPMP5694987      33
ECOH5525375      30
EPMP5013310      30
IYK              23
TSRYS5352542      8
TSRYS4494279      8
TSRYS5677393      2
ISQWF             2
TSRYS5371093      2
TSRYS5668797      2
TSRYS5557560      2
ISVQF             2
ISZXF             1
P9379RBC0         1
Name: count, dtype: int64

In [20]:
internacional['nombre_activo'].value_counts()

nombre_activo
BNY MELLON US DOLLAR LIQD SERV                                                            720
BGF CONTINENTAL EUROPEAN FLEXIBLE FUND CLASS A2 (HEDGED) (USD)                            195
BGF GLOBAL ALLOCATION FUND CLASS A2 (USD)                                                 195
NINETY ONE GSF GLOBAL FRANCHISE FUND CLASS A (ACC)(USD)                                   169
BGF GLOBAL MULTI ASSET INCOME FUND CLASS A2 (USD)                                         130
                                                                                         ...
BLACKROCK STRATEGIC MANAGED INDEX PORT DEFENSIVE FD CL A2 (USD)(HEDG)                       1
Liquidez                                                                                    1
330000000                                                                                   1
BANCO GNB SUDAMERIS REG S BOND ISIN#USP1265VAD49 0.000% 04/03/27 REG DTD 04/03/17 CLB       1
180000                                                                                      1
Name: count, Length: 110, dtype: int64

In [21]:
internacional['tasa_cupon'].value_counts()

tasa_cupon
0            4621
6.25          138
11.2          128
8.875          65
5.65           65
4.25           65
5.5            65
4.95           65
5.125          65
7.45           65
4.375          64
7.051          64
9.75           64
7.5            61
5.6            53
5.4            40
6.1            35
1.5             8
1.625           8
4.625           2
1.75            2
5               2
3.875           2
1/01/1900       1
Name: count, dtype: int64

In [22]:
internacional['cantidad'].value_counts()

cantidad
0                                 805
50000                             647
200000                            428
500                               239
100000                            146
                                 ...
2310.814                            1
227                                 1
BNY MELLON US DOLLAR LIQD SERV      1
75933                               1
134638.2                            1
Name: count, Length: 98, dtype: int64

In [23]:
internacional['fecha_vencimiento'].value_counts()

fecha_vencimiento
1/01/1900     4177
12/09/2024     130
6/06/2024      128
4/01/2024      126
01/13/2033      65
01/24/2025      65
09/16/2024      65
5/12/2026       65
6/09/2026       65
07/31/2027      65
02/18/2025      65
07/17/2030      65
01/15/2028      65
4/03/2027       65
11/15/2029      65
04/16/2031      65
02/15/2031      64
07/26/2028      64
01/29/2024      53
06/19/2025      46
12/07/2023      40
11/13/2024      35
6/04/2025       27
6/06/2025       27
10/02/2023      20
02/15/2025       8
02/15/2026       8
10/23/2025       4
11/15/2026       2
03/15/2025       2
10/31/2025       2
03/31/2025       2
09/15/2025       2
816.94           1
9.75             1
4.375            1
Name: count, dtype: int64